export const commentTemplates = [
  "🔎 Full story here:",
  "📖 Read the complete version here:",
  "📰 Full coverage at:",
  "📊 In-depth breakdown here:",
  "🧠 More insights in the full article:",
  "📌 Additional details here:",
  "🔥 Full explanation here:",
  "👀 If you're curious, full story here:",
  "💡 Everything explained in detail here:",
  "📚 Background and full context:",
  "🚨 Full update here:",
  "✨ Complete write-up here:",
  "👉 Full article here:",
  "🔍 More context available at:",
  "📎 Full details here:",
  "📝 Full write-up available here:",
  "📢 Complete coverage here:",
  "🧾 Full report here:",
  "📈 Detailed article here:",
  "📉 Full breakdown here:",
  "🔥 All the details here:",
  "📍 More information here:",
  "🖊️ Full explanation in the article:",
  "📘 Full version here:",
  "📓 Complete overview here:",
  "👓 Take a closer look here:",
  "🧩 Full context explained here:",
  "🛠️ Step-by-step breakdown here:",
  "📦 Everything you need to know here:",
  "📣 Full update and details here:",
  "🧭 Explore the full story here:",
  "📜 Full background here:",
  "🔦 More insight available here:",
  "📄 Read the full piece here:",
  "📥 Full article linked here:",
  "👀 Dive deeper here:",
  "🔗 Access the full story here:",
  "🧠 Full insight here:",
  "📚 Get the complete details here:",
  "📰 Read the full coverage here:",
  "📌 Full explanation linked here:",
  "💬 Full discussion here:",
  "🧾 Complete details here:",
  "📍 Full context available here:",
];

export const captionLinkCTAs = [
  "🔎 Full story here",
  "📖 Read more",
  "📰 Full coverage",
  "📊 More details",
  "👀 Take a look",
  "👉 Continue reading",
  "💡 Full breakdown",
  "📌 Full article",
  "🧠 In-depth explanation",
  "📚 Complete write-up",
  "🚨 Latest update",
  "✨ Full report",
  "📈 Detailed analysis",
  "📉 Full breakdown available",
  "🧾 Complete details",
  "📍 Full context",
  "🔍 Dive deeper",
  "📎 Full piece",
  "🗂️ All the details",
  "📣 Full coverage available",
  "Read the full story",
  "Get the full details",
  "See the full report",
  "More insights here",
  "Explore the full article",
  "Full explanation below",
  "Everything explained here",
  "Access the full story",
  "Full version available",
  "Check out the full article",
  "🔥 Don't miss the full story",
  "🚨 Breaking update here",
  "👀 You'll want to read this",
];

export const captionCommentCTAs = [
  "🔗 Full story in the pinned comment.",
  "📌 Link in the first comment.",
  "👇 More details below.",
  "💬 Check the comments for the full article.",
  "📖 Complete coverage in the comments.",
  "🧾 See pinned comment for full story.",
  "📎 Link posted below.",
  "📊 Full breakdown in the comments.",
  "📰 Details in the first comment.",
  "🔍 Read more in the comments.",
  "📘 Full article in the pinned comment.",
  "💡 More info in comments.",
  "📝 Complete write-up below.",
  "📍 Full coverage in the first comment.",
  "⬇️ Link in comments.",
  "👀 See below for full details.",
  "📚 Full story shared in comments.",
  "🗂️ Check below for more.",
  "🧠 More context in the comments.",
  "✨ Full explanation in comments.",
  "📣 Story continues in the pinned comment.",
  "🚨 Extra details posted below.",
  "📄 Read the rest in comments.",
  "🧩 Full version in comments.",
  "🔦 More insights shared below.",
  "🔎 Link available in comments.",
  "🗞️ Full report posted in comments.",
  "➡️ Continue reading in the comments.",
  "📢 Full story in comments.",
  "📌 See first comment for details.",
  "Full story in the comments.",
  "Link is in the first comment.",
  "More details in the comments.",
  "See comments for the full article.",
  "Complete story below.",
  "Check the first comment.",
];

export const softCTAs = [
  "What do you think about this?",
  "Thoughts on this?",
  "Your take on this?",
  "Do you agree or disagree?",
  "Is this the right move?",
  "How would you react?",
  "Would you support this?",
  "Is this surprising to you?",
  "Fair decision or not?",
  "Does this make sense?",
  "Too much or just right?",
  "Is this justified?",
  "What’s your opinion?",
  "Would you handle this differently?",
  "Do you see this as a big deal?",
  "Is this being blown out of proportion?",
  "How do you feel about this?",
  "Is this overdue?",
  "Does this change anything?",
  "Would this affect you?",
  "Is this the outcome you expected?",
  "What stands out to you the most?",
  "Do you think this will last?",
  "Is this a smart move?",
  "What would you do in this situation?",
  "Is this a step forward or backward?",
  "How should this have been handled?",
  "Agree or not?",
  "Is this something we should be talking about?",
  "Drop your thoughts below.",
  "Let us know what you think.",
  "Share your perspective.",
  "Curious to hear your opinion.",
  "Open for discussion.",
  "Let’s talk about it.",
  "We’d like to hear your view.",
  "Sound off in the comments.",
  "Join the conversation.",
  "What’s your honest take?",
  "Would you call this fair?",
  "Is this getting the reaction it deserves?",
  "Does this surprise you?",
  "What’s the bigger picture here?",
  "Is this the right direction?",
  "How would you respond to this?",
  "Are people overreacting?",
  "Should this have happened?",
  "Is this being handled properly?",
  "Would you have done the same?",
  "What’s missing from this story?",
];

export const blacklistKeywordTag = [
  // Adult
  "porn",
  "porno",
  "sex",
  "xxx",
  "nude",
  "naked",
  "onlyfans",
  "hentai",
  "milf",
  "escort",
  "camgirl",
  "cam sex",
  "blowjob",
  "handjob",
  "anal",
  "bdsm",
  "fetish",
  "masturbation",
  "hookup",
  "dating sex",
  "sexy",
  "hot girl",
  "hot girls",
  "leaked",
  "leak",
  "private video",

  // Underage
  "underage",
  "teen sex",
  "child porn",
  "lolita",

  // Gambling
  "casino",
  "bet",
  "betting",
  "sports betting",
  "odds",
  "gambling",
  "poker",
  "blackjack",
  "roulette",
  "slot",
  "slots",
  "bookmaker",

  // Drugs
  "drug",
  "drugs",
  "cocaine",
  "heroin",
  "meth",
  "marijuana",
  "weed",
  "lsd",
  "ecstasy",

  // Violence
  "kill",
  "murder",
  "suicide",
  "self harm",
  "gore",
  "torture",
  "beheading",
  "execution",
  "mass shooting",

  // Weapons
  "gun",
  "rifle",
  "pistol",
  "weapon",
  "bomb",
  "explosive",
  "grenade",
  "ammo",
  "ammunition",

  // Illegal
  "hack",
  "hacker",
  "crack",
  "keygen",
  "carding",
  "phishing",
  "stolen account",
  "free account",
  "account generator",

  // Piracy
  "torrent",
  "warez",
  "serial key",
  "license key",
  "cracked",
  "nulled",
  "mod apk",
  "apk mod",
  "premium apk",

  // Terrorism
  "terrorist",
  "terrorism",
  "isis",
  "al qaeda",
  "extremist",

  // Spam SEO
  "download free",
  "free download",
  "watch free",
  "stream free",
  "watch online free",

  // Crypto scam
  "airdrop",
  "free bitcoin",
  "free crypto",
  "crypto signal",
  "pump signal",

  // Fake generators
  "generator",
  "cheat",
  "unlimited money",
  "unlimited coins",
  "mod menu",

  //Undefinited
  "stadium",
];

export const whitelistKeywordTag = [];
